### ISSUE TITLE
run.sh php.ini update error (7.2 should be 7.3)

### ISSUE THREAD

**Issue by kulnor** [mattrayner/docker-lamp#74] opened 2019-11-18 19:59 UTC
The error below is shown when the container starts (from run.sh):

> sed: can't read /etc/php/7.2/apache2/php.ini: No such file or directory

Should be changed to /7.3/

**Comment by pzhlkj6612** [comment] 2019-11-19 04:27
Hi, @kulnor . The author wrote new code for this error in `mattrayner/refactor` branch.

https://github.com/mattrayner/docker-lamp/blob/353c7a51937708c9fef7182e9a2a69e0c3faf4a5/supporting_files/run.sh#L8-L44

And the env `PHP_VERSION` is here.

https://github.com/mattrayner/docker-lamp/blob/353c7a51937708c9fef7182e9a2a69e0c3faf4a5/1804/Dockerfile#L15

It seems that the author does not have time to maintain this repo, so you can switch to the `mattrayner/refactor` branch and do some testing by yourself.

**Comment by mattrayner** [comment] 2019-11-21 00:31
Hey @kulnor and @pzhlkj6612 I'll pick up the refactor work over the next couple of days and try and get this pushed through

**Comment by jnachtigall** [comment] 2019-12-07 13:40
Hitting this as well, seems to be a duplicate of #62 

Does this actually have any negative impact? Docker seems to be running nonetheless

**Comment by mahmoudajawad** [comment] 2020-03-12 13:51
Any update on this?

**Comment by mahmoudajawad** [comment] 2020-03-13 06:43
Just in case anyone else is using this repo and want a quick fix, you can have a look at #78

**Comment by mattrayner** [comment] 2020-03-14 22:46
I’ve released a fix based on @mahmoudajawad’s PR that fixes this

The refactor has been delayed as I had a son and have lost a lot of free time 😂

**Closed** 2020-03-14 22:47 UTC
